"""Archivey — Python library for reading, streaming, and safely extracting archives."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("archivey")
except PackageNotFoundError:
    __version__ = "0.0.0+unknown"

from archivey.config import (
    DEFAULT_ARCHIVEY_CONFIG,
    AcceleratorMode,
    ArchiveyConfig,
    ExtractionLimits,
    ListingLimits,
    PasswordProvider,
    PasswordRequest,
)
from archivey.core import (
    DetectionConfidence,
    FormatAvailability,
    FormatInfo,
    FormatSupport,
    MissingComponent,
    detect_format,
    extract,
    format_availability,
    list_known_formats,
    list_supported_formats,
    open_archive,
    open_stream,
)
from archivey.cost import (
    AccessCost,
    CostReceipt,
    ListingCost,
    StreamCapability,
)
from archivey.diagnostics import (
    ArchiveEofContext,
    Diagnostic,
    DiagnosticCode,
    DiagnosticContext,
    DiagnosticDisposition,
    DiagnosticPolicy,
    DiagnosticSeverity,
    DiagnosticSummary,
    DigestContext,
    ExtractionOutcomeContext,
    ExtractionReport,
    FormatConflictContext,
    MemberTimestampContext,
    NameNormalizationContext,
    ScanRaceContext,
    SeekIndexContext,
    StreamRewindContext,
    SymlinkTargetContext,
)
from archivey.exceptions import (
    ArchiveyError,
    ArchiveyUsageError,
    ConcurrentAccessError,
    CorruptionError,
    DiagnosticRaisedError,
    EncryptionError,
    ExtractionError,
    FilterRejectionError,
    FormatDetectionError,
    LinkTargetNotFoundError,
    OpenError,
    PackageNotInstalledError,
    PathTraversalError,
    ReadError,
    ResourceLimitError,
    SpecialFileError,
    StreamNotSeekableError,
    SymlinkEscapeError,
    TruncatedError,
    UnsupportedFeatureError,
    UnsupportedFormatError,
    UnsupportedOperationError,
    WriteError,
)
from archivey.internal.extraction_types import (
    ExtractionPolicy,
    ExtractionProgress,
    ExtractionResult,
    ExtractionStatus,
    MemberFilter,
    OnError,
    OverwritePolicy,
)
from archivey.internal.streams.archive_stream import ArchiveStream
from archivey.reader import ArchiveReader, MemberSelector
from archivey.types import (
    ArchiveFormat,
    ArchiveInfo,
    ArchiveMember,
    CompressionAlgorithm,
    CompressionMethod,
    ContainerFormat,
    CreateSystem,
    MemberStreams,
    MemberType,
    StreamFormat,
)

__all__ = [
    "__version__",
    "open_archive",
    "open_stream",
    "extract",
    "ArchiveyConfig",
    "DEFAULT_ARCHIVEY_CONFIG",
    "ExtractionLimits",
    "ListingLimits",
    "AcceleratorMode",
    "PasswordRequest",
    "PasswordProvider",
    "ExtractionPolicy",
    "OverwritePolicy",
    "OnError",
    "ExtractionStatus",
    "ExtractionProgress",
    "ExtractionResult",
    "ExtractionReport",
    "MemberSelector",
    "MemberFilter",
    "detect_format",
    "FormatInfo",
    "DetectionConfidence",
    "format_availability",
    "list_supported_formats",
    "list_known_formats",
    "FormatSupport",
    "FormatAvailability",
    "MissingComponent",
    "ArchiveReader",
    "ArchiveStream",
    "ArchiveFormat",
    "ContainerFormat",
    "StreamFormat",
    "ArchiveMember",
    "ArchiveInfo",
    "MemberType",
    "MemberStreams",
    "CompressionAlgorithm",
    "CompressionMethod",
    "CreateSystem",
    "CostReceipt",
    "ListingCost",
    "AccessCost",
    "StreamCapability",
    "Diagnostic",
    "DiagnosticCode",
    "DiagnosticContext",
    "DiagnosticSeverity",
    "DiagnosticDisposition",
    "DiagnosticPolicy",
    "DiagnosticSummary",
    "DiagnosticRaisedError",
    "ArchiveEofContext",
    "DigestContext",
    "ExtractionOutcomeContext",
    "FormatConflictContext",
    "MemberTimestampContext",
    "NameNormalizationContext",
    "ScanRaceContext",
    "SeekIndexContext",
    "StreamRewindContext",
    "SymlinkTargetContext",
    "ArchiveyError",
    "ArchiveyUsageError",
    "ConcurrentAccessError",
    "OpenError",
    "FormatDetectionError",
    "UnsupportedFormatError",
    "StreamNotSeekableError",
    "ReadError",
    "CorruptionError",
    "TruncatedError",
    "EncryptionError",
    "LinkTargetNotFoundError",
    "WriteError",
    "ExtractionError",
    "FilterRejectionError",
    "PathTraversalError",
    "SymlinkEscapeError",
    "SpecialFileError",
    "ResourceLimitError",
    "UnsupportedFeatureError",
    "PackageNotInstalledError",
    "UnsupportedOperationError",
]

# Register the bundled backends eagerly (each module self-registers on import), so the
# availability queries (list_supported_formats / format_availability) work immediately
# after `import archivey`, without first calling open_archive().
import archivey.internal.backends  # noqa: E402,F401

# Keep the importlib.metadata helpers out of the public `archivey` namespace
# (so `__all__` stays the single, hand-curated description of the public API).
del PackageNotFoundError, version
