#!/usr/bin/env python3
"""Run dedicated native-heavy pytest modules in fresh subprocesses (CI bandage).

Used by the ``[all]`` / ``[all-lowest]`` CI legs after the main suite. Each listed
module gets its **own** interpreter so a heap-poisoning module cannot take down
the others, and so the Actions log names the offender.

Differences from a single ``pytest a.py b.py c.py``:

- Coverage is **off** (``-o addopts=…`` without pytest-cov). The observed abort is
  often ``corrupted size vs. prev_size`` during ``coverage`` flush / GC *after*
  every test already passed — a late tripwire, not a useful failure site.
- A tiny ``-p`` plugin records the last completed / started nodeid under the
  work dir so a mid-suite SIGSEGV/SIGABRT still leaves a breadcrumb.
- Per-module rc / signal formatting mirrors ``scripts/ppmd_native_stress.py``.
- Children keep running after a failure so one poisoned module does not hide
  whether the others are clean.

::

    uv run --no-sync python scripts/ci_run_native_modules.py
    uv run --no-sync python scripts/ci_run_native_modules.py --timeout 120

Exit 0 only if every module child exits 0.
"""

from __future__ import annotations

import argparse
import os
import platform
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]

_DEFAULT_MODULES: tuple[str, ...] = (
    "tests/test_rapidgzip_deflate_zlib.py",
    "tests/test_accelerator_shutdown.py",
    "tests/test_accelerator_corruption.py",
    "tests/test_ppmd_raw_streams.py",
)

_WINDOWS_NTSTATUS: dict[int, str] = {
    0xC0000005: "STATUS_ACCESS_VIOLATION",
    0xC0000374: "STATUS_HEAP_CORRUPTION",
    0xC0000409: "STATUS_STACK_BUFFER_OVERRUN",
    0xC00000FD: "STATUS_STACK_OVERFLOW",
}


def _safe_print(msg: str, *, file=None) -> None:
    stream = file or sys.stdout
    encoding = getattr(stream, "encoding", None) or "utf-8"
    try:
        stream.write(msg + "\n")
    except UnicodeEncodeError:
        stream.write(msg.encode(encoding, errors="replace").decode(encoding) + "\n")
    stream.flush()


def _format_rc(returncode: int) -> str:
    unsigned = returncode & 0xFFFFFFFF
    if returncode < 0 or returncode > 255:
        name = _WINDOWS_NTSTATUS.get(unsigned)
        if name is not None:
            return f"0x{unsigned:08X} ({name}); signed={returncode}"
        if -64 < returncode < 0:
            return f"{returncode} (likely signal {-returncode})"
        return f"0x{unsigned:08X} (unknown); signed={returncode}"
    return str(returncode)


def _last_test_plugin(path: Path) -> None:
    """Write a pytest plugin that records the last nodeid into ``path``'s sibling."""
    nodeid_path = path.parent / "last_nodeid.txt"
    path.write_text(
        textwrap.dedent(
            f"""\
            # Auto-generated by scripts/ci_run_native_modules.py — last-test breadcrumb.
            from __future__ import annotations

            import os
            from pathlib import Path

            _PATH = Path({str(nodeid_path)!r})


            def _write(msg: str) -> None:
                with _PATH.open("w", encoding="utf-8") as fh:
                    fh.write(msg)
                    fh.flush()
                    os.fsync(fh.fileno())


            def pytest_runtest_logstart(nodeid: str, location) -> None:
                _write(f"start {{nodeid}}")


            def pytest_runtest_logfinish(nodeid: str, location) -> None:
                _write(f"done {{nodeid}}")


            def pytest_sessionfinish(session, exitstatus) -> None:
                prev = _PATH.read_text(encoding="utf-8") if _PATH.exists() else ""
                _write(f"sessionfinish exit={{exitstatus}} last={{prev!r}}")
            """
        ),
        encoding="utf-8",
    )


def _run_module(
    module: str,
    *,
    work: Path,
    timeout: float,
    extra_pytest_args: list[str],
) -> tuple[int, str]:
    mod_dir = work / module.replace("/", "_").replace(".", "_")
    mod_dir.mkdir(parents=True, exist_ok=True)
    plugin = mod_dir / "last_test_plugin.py"
    _last_test_plugin(plugin)
    last_path = mod_dir / "last_nodeid.txt"

    env = os.environ.copy()
    env.setdefault("PYTHONFAULTHANDLER", "1")
    env.setdefault("PYTHONIOENCODING", "utf-8")
    # Keep coverage files from colliding / flushing a poisoned heap across children.
    env["COVERAGE_FILE"] = str(mod_dir / ".coverage")
    # Make the generated plugin importable via ``-p last_test_plugin``.
    env["PYTHONPATH"] = os.pathsep.join(
        [str(mod_dir), *(p for p in [env.get("PYTHONPATH")] if p)]
    )

    cmd = [
        sys.executable,
        "-m",
        "pytest",
        module,
        # Drop pytest-cov from addopts: flush/GC after a poisoned run is the usual
        # fatal site ("corrupted size vs. prev_size" in coverage.collector).
        "-o",
        "addopts=--timeout=60",
        "-p",
        "last_test_plugin",
        "--tb=short",
        "-q",
        *extra_pytest_args,
    ]
    _safe_print(f"  cmd: {' '.join(cmd)}")

    try:
        # Stream child output live into the CI log (do not capture).
        proc = subprocess.run(
            cmd,
            cwd=str(_REPO_ROOT),
            env=env,
            timeout=timeout,
            check=False,
        )
        rc = proc.returncode
    except subprocess.TimeoutExpired:
        _safe_print(f"  TIMEOUT after {timeout}s", file=sys.stderr)
        rc = -1

    last = last_path.read_text(encoding="utf-8") if last_path.exists() else "<none>"
    return rc, last


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--modules",
        nargs="+",
        default=list(_DEFAULT_MODULES),
        help="Pytest module paths relative to the repo root",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=float(os.environ.get("ARCHIVEY_NATIVE_MODULE_TIMEOUT", "300")),
        help="Per-module subprocess timeout in seconds (default: 300)",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=None,
        help="Optional Markdown summary path",
    )
    parser.add_argument(
        "pytest_args",
        nargs="*",
        help="Extra args forwarded to each pytest child after `--`",
    )
    args = parser.parse_args(argv)

    modules = list(dict.fromkeys(args.modules))
    _safe_print(
        f"native-module batch: modules={modules!r} "
        f"platform={platform.platform()!r} python={sys.version.split()[0]} "
        f"executable={sys.executable!r}"
    )
    _safe_print(
        "Note: coverage is disabled in children; last-nodeid breadcrumbs survive "
        "SIGSEGV/SIGABRT. See docs/internal/known-issues.md."
    )

    results: list[tuple[str, int, str]] = []
    with tempfile.TemporaryDirectory(prefix="archivey-native-modules-") as tmp:
        work = Path(tmp)
        for module in modules:
            _safe_print(f"\n=== module {module} ===")
            rc, last = _run_module(
                module,
                work=work,
                timeout=args.timeout,
                extra_pytest_args=args.pytest_args,
            )
            results.append((module, rc, last))
            if rc == 0:
                _safe_print(f"PASSED: {module}  last={last!r}")
            else:
                _safe_print(
                    f"FAILED: {module}  rc={_format_rc(rc)}  "
                    f"Last test before abort: {last!r}"
                )

    lines = [
        "# Native-module batch results",
        "",
        f"- platform: `{platform.platform()}`",
        f"- python: `{sys.version.split()[0]}`",
        "",
        "| Module | Result | Last nodeid |",
        "| --- | --- | --- |",
    ]
    failed = 0
    for module, rc, last in results:
        if rc == 0:
            lines.append(f"| `{module}` | OK | `{last}` |")
        else:
            failed += 1
            lines.append(f"| `{module}` | **FAIL** `{_format_rc(rc)}` | `{last}` |")
    lines.append("")
    lines.append(
        "Coverage is disabled in these children: a poisoned heap often only aborts "
        "during pytest-cov flush/GC after every test passed. Split modules + "
        "last-nodeid breadcrumbs are for locating the offender. See "
        "`docs/internal/known-issues.md`."
    )
    summary = "\n".join(lines) + "\n"

    if args.summary is not None:
        args.summary.write_text(summary, encoding="utf-8")
    gh_summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if gh_summary:
        with open(gh_summary, "a", encoding="utf-8") as fh:
            fh.write(summary)
    _safe_print("\n" + summary)
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
